# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all # Apply fixes automatically
FILEIO_REPORTER: false # Generate file.io report
GITHUB_STATUS_REPORTER: true # Generate GitHub status report
IGNORE_GENERATED_FILES: true # Ignore generated files
JAVASCRIPT_DEFAULT_STYLE: prettier # Default style for JavaScript
PRINT_ALPACA: false # Print Alpaca logo in console
SARIF_REPORTER: true # Generate SARIF report
SHOW_ELAPSED_TIME: false # Show elapsed time at the end of MegaLinter run
SHOW_SKIPPED_LINTERS: false # Show skipped linters in MegaLinter log

# Tooling configuration
REPOSITORY_KICS_DISABLE_ERRORS: true # Show errors as warnings in KICS

# Linters that are run, but not reported on
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM

# List of linters to disable. These are not typical in my repos,
# except for spelling errors and copypasta. I'm handling those
# with other tools.
DISABLE:
  - ARM
  - C
  - CLOJURE
  - COFFEE
  - COPYPASTE
  - DART
  - GROOVY
  - JAVA
  - KOTLIN
  - R
  - SALESFORCE
  - SCALA
  - SNAKEMAKE
  - SPELL
  - SWIFT
  - TEKTON
  - VBDOTNET

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
