---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
#
# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a Pull Request if any images can be compressed.
name: Compress Images on Demand

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * 0"

permissions:
  contents: read
  statuses: read
  pull-requests: read

jobs:
  CompressOnDemandOrSchedule:
    name: calibreapp/image-actions

    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          title: Compressed Images Nightly
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
