---
name: Run Composer Install

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "composer.json"
      - "composer.lock"

permissions: {}

jobs:
  ComposerInstall:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write

    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-
            ${{ runner.os }}-php-

      - name: Composer (PHP ${{ matrix.php }})
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --no-progress --prefer-dist --optimize-autoloader
