---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run Composer Install

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "composer.json"
      - "composer.lock"

permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  ComposerInstall:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      statuses: write

    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php: ["8.1", "8.2", "8.3", "8.4"]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-
            ${{ runner.os }}-php-

      - name: Composer (PHP ${{ matrix.php }})
        uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6
        with:
          php_version: ${{ matrix.php }}
          args: --no-progress --prefer-dist --optimize-autoloader
