---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Compress Images

on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"

permissions:
  contents: read
  packages: read
  statuses: read
  pull-requests: read

jobs:
  CompressInPR:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
