---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reviewdog Linters

on: [pull_request]

permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: GitHub Actions
        uses: reviewdog/action-actionlint@abd537417cf4991e1ba8e21a67b1119f4f53b8e0 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: markdownlint
        uses: reviewdog/action-markdownlint@f901468edf9a3634dd39b35ba26cad0aad1a0bfd # v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: shfmt
        uses: reviewdog/action-shfmt@f59386f08bd9a24ac1a746e69f026ddc2ed06710 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shfmt_flags: |
            --find
            --list
            --write
            --diff
            --language-dialect bash
            --indent 2
            --binary-next-line
            --case-indent
            --space-redirects
            --func-next-line

      - name: yamllint
        uses: reviewdog/action-yamllint@1dca3ad811867be18fbe293a9818d715a6c2cd46 # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
